name: CD - Terraform Deployment

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  # This job runs a terraform plan on pull requests to the prod branch
  terraform-plan-for-dev:
    name: 'Terraform Plan for DEV'
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: dev # Use the 'dev' environment and its secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
        env:
        AWS_ACCESS_KEY_ID: ASIAYWE3BNF7FBUR3OTD
        AWS_SECRET_ACCESS_KEY: woV6jrvgJ3cyMQknKfXw1OzEf5wwUQ4qLOhCILJ7


  # This job deploys to the staging environment after a merge to prod
  terraform-apply-to-staging:
    name: 'Terraform Apply to STAGING'
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: staging # Use the 'staging' environment and its secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
       env:
        AWS_ACCESS_KEY_ID: ASIAYWE3BNF7FBUR3OTD
        AWS_SECRET_ACCESS_KEY: woV6jrvgJ3cyMQknKfXw1OzEf5wwUQ4qLOhCILJ7


  # This job deploys to the prod environment after a merge to prod
  terraform-apply-to-prod:
    name: 'Terraform Apply to PROD'
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: prod # Use the 'prod' environment and its secrets
    needs: terraform-apply-to-staging # Wait for staging deployment to succeed first

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
         env:
        AWS_ACCESS_KEY_ID: ASIAYWE3BNF7FBUR3OTD
        AWS_SECRET_ACCESS_KEY: woV6jrvgJ3cyMQknKfXw1OzEf5wwUQ4qLOhCILJ7
